name: persian_date_null_saftey
description: This Plugin is Used For Jalali Date support null saftey
version: 1.1.0
author: Hasan Hoseini <3hhosaini@gmail@gmail.com>
# Telegram: t.me/Developer_89

environment:
 sdk: '>=2.18.1 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
 test: ^1.0.0
